### ISSUE TITLE
🐛 [BUG] - cannot install from brew

### ISSUE THREAD

**Issue by kingtosh** [romankurnovskii/BrewMate#120]
### Description

Error: SHA256 mismatch
Expected: 22c4b130db5193122a539fee35f47efc5d0423fdcded1b94dc174972f6a6e25f
  Actual: 746d82bcfe7428f05d42ee29cab337b92e6f99b02440da5533760d0678193091

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### OS

Mac

**Comment by romankurnovskii** [comment]
which app?

**Comment by tkennertas** [comment]
BrewMate

```shell
brew install romankurnovskii/cask/brewmate --cask --no-quarantine
==> Downloading https://github.com/romankurnovskii/BrewMate/releases/download/0.3.7/BrewMate-0.3.7-universal-mac.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/613569916/ef7cba9d-adba-4c53-87cd-40d30bf91aea?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential
########################################################################################################################################################################################### 100.0%
Error: SHA256 mismatch
Expected: 22c4b130db5193122a539fee35f47efc5d0423fdcded1b94dc174972f6a6e25f
  Actual: 746d82bcfe7428f05d42ee29cab337b92e6f99b02440da5533760d0678193091
    File: /Users/USERNAME/Library/Caches/Homebrew/downloads/b6990577d7f94b8fc2f5d8c35acb190a6d39f1c3060d42e135c39c4161f4dc9e--BrewMate-0.3.7-universal-mac.zip
To retry an incomplete download, remove the file above.
```

**Comment by romankurnovskii** [comment]
> BrewMate
> 
> ```shell
> brew install romankurnovskii/cask/brewmate --cask --no-quarantine
> ==> Downloading https://github.com/romankurnovskii/BrewMate/releases/download/0.3.7/BrewMate-0.3.7-universal-mac.zip
> ==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/613569916/ef7cba9d-adba-4c53-87cd-40d30bf91aea?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential
> ########################################################################################################################################################################################### 100.0%
> Error: SHA256 mismatch
> Expected: 22c4b130db5193122a539fee35f47efc5d0423fdcded1b94dc174972f6a6e25f
>   Actual: 746d82bcfe7428f05d42ee29cab337b92e6f99b02440da5533760d0678193091
>     File: /Users/USERNAME/Library/Caches/Homebrew/downloads/b6990577d7f94b8fc2f5d8c35acb190a6d39f1c3060d42e135c39c4161f4dc9e--BrewMate-0.3.7-universal-mac.zip
> To retry an incomplete download, remove the file above.
> ```

fixed it here: https://github.com/romankurnovskii/homebrew-cask/pull/15/files


thank you

**Comment by tkennertas** [comment]
Thank you. With the fixed checksum and the fixed command in the README file it works now!

```shell
brew install romankurnovskii/awesome-brew/brewmate --cask --no-quarantine

==> Downloading https://github.com/romankurnovskii/BrewMate/releases/download/0.3.7/BrewMate-0.3.7-universal-mac.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/613569916/ef7cba9d-adba-4c53-87cd-40d30bf91aea?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Creden
####################################################################################################################################################################################### 100.0%
==> Installing Cask brewmate
Warning: macOS's Gatekeeper has been disabled for this Cask
==> Moving App 'BrewMate.app' to '/Applications/BrewMate.app'
🍺  brewmate was successfully installed!
```

**Comment by kingtosh** [comment]
thank you!

**Comment by kingtosh** [comment]
thank you!
